-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 21:39:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Funcionario` (
  `id_Funcionario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dependente` (
  `id_Dependente` INT NOT NULL,
  `Nome_Dependente` VARCHAR(45) NULL,
  `Funcionario_id_Funcionario` INT NOT NULL,
  PRIMARY KEY (`id_Dependente`, `Funcionario_id_Funcionario`),
  INDEX `fk_Dependente_Funcionario_idx` (`Funcionario_id_Funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Dependente_Funcionario`
    FOREIGN KEY (`Funcionario_id_Funcionario`)
    REFERENCES `Funcionario` (`id_Funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
